{{- if .Values.ingress.enabled -}}
{{- $fullName := include "metfrag.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "metfrag.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - host: {{ index .Values.ingress.hosts 0 "host"| quote }}
    http:
      paths:
        - path: {{ .Values.RESTpath }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.RESTname }}
              port:
                number: {{ $svcPort }}
        - path: {{ .Values.webpath }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}

{{- end }}
