apiVersion: v1
kind: ConfigMap
metadata:
  name: metfrag-settings
data:
  # Set as complete file contents (even JSON!)
  settings.properties: |
    NumberThreads = {{ .Values.NumberThreads }}
    UseSmiles = True
    MetFragCandidateWriter = XLS
    FeedbackEmailTo = {{ .Values.FeedbackEmailTo }}
    FeedbackEmailHost = {{ .Values.FeedbackEmailHost }}
    # metchem database settings
    LocalMetChemDatabase=metchem
    LocalMetChemDatabasePortNumber=5432
    LocalMetChemDatabaseServerIp=metfrag-postgresql
    LocalMetChemDatabaseUser=metchemro
    LocalMetChemDatabasePassword=metchemro
    # local database file folder
    LocalDatabasesFolderForWeb = /vol/file_databases
    # Spectral library folder
    OfflineSpectralDatabaseFile = /vol/spectral_databases
