apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.RESTname }}
  labels:
    {{- include "metfragrest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "metfragrest.selectorLabels" . | nindent 4 }}
