{{- if .Values.ingress.enabled -}}
{{- $fullName := include "metfrag.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "metfrag.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ index .Values.ingress.hosts 0 "host"| quote }}
    secretName: {{ .secretName }}
{{- end }}
  rules:
  - host: {{ index .Values.ingress.hosts 0 "host"| quote }}
    http:
      paths:
        - path: {{ .Values.webpath }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
{{- end }}
