apiVersion: v2
name: metfrag
description: A Helm chart for the MetFrag application
type: application
version: 0.1.1.1
appVersion: latest
icon: https://msbi.ipb-halle.de/MetFragLogo232x128.png

dependencies:
  - name: postgresql
    version: 8.6.1
    repository: http://storage.googleapis.com/kubernetes-charts
