apiVersion: v1
kind: Service
metadata:
  name: {{ include "metfamily.fullname" . }}
  labels:
    {{- include "metfamily.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3838
      protocol: TCP
      name: http
  selector:
    {{- include "metfamily.selectorLabels" . | nindent 4 }}
